create database customer_behaviour_db;
use customer_behaviour_db;

select * from customer_data
limit 10

# 1.Total revenue generated by male vs female customers
select gender , sum(purchase_amount) as revenue
from customer_data
group by gender;

# 2. Which customers used a discount but still spent more that the average purchase amount?
select customer_id,discount_applied,purchase_amount
from customer_data
where discount_applied = "yes" and purchase_amount >=(select avg(purchase_amount) from customer_data)

# 3. what are the top 5 products with the highest average review rating
select item_purchased,round(avg(review_rating),2) as avg_rating from customer_data
group by item_purchased
order by round(avg(review_rating),2) desc
limit 5;

# 4. compare the average purchase amounts between standard and express shipping
select shipping_type , round(avg(purchase_amount),2) from customer_data
where shipping_type in ("standard" , "Express")
group by shipping_type

# 5. Do subsribed customers spend more ? compare average spend and total revenue between subscribers and non-subscribers
select subscription_status,count(customer_id),avg(purchase_amount) as avg_spend , sum(purchase_amount) as total_revenue
from customer_data
group by subscription_status

# 6. which 5 products have the highest percentage of purchase with discounts applied
SELECT 
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(*),
        2
    ) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

# 7. segment customers into new, returning,loyal based on their total ,number of previous purchases , and show the count of each segment.
with customers_segment as (
	select previous_purchases,
    case
		when previous_purchases = 1 then "New"
        when previous_purchases between 2 and 10 then "Returning"
        else "Loyal"
        end as customer_segment
from customer_data)

select customer_segment,count(*) as no_of_customers from customers_segment
group by customer_segment

# 8. what are the top 3 most purchased products within each category
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer_data
group by category ,item_purchased)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3

# 9 . are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_data
where previous_purchases >5
group by subscription_status

# 10 . what is the revenue contribution of each age group 
select age_group,sum(purchase_amount) as revenue
from customer_data
group by age_group
order by revenue desc



